apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb7014
  namespace: argocd
spec:
  destination:
    namespace: mongo7014
    server: https://kubernetes.default.svc
  project: databases
  source:
    path: cluster/databases/mongo/7.0.14
    repoURL: file:///tmp/k8sexperiments.git
    targetRevision: HEAD
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true
