apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis741repl
  namespace: argocd
spec:
  destination:
    namespace: redis741repl
    server: https://kubernetes.default.svc
  project: databases
  source:
    path: cluster/databases/redis/7.4.1-replication
    repoURL: file:///tmp/k8sexperiments.git
    targetRevision: HEAD
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true
