apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb803
  namespace: argocd
spec:
  destination:
    namespace: mongo803
    server: https://kubernetes.default.svc
  project: databases
  source:
    path: cluster/databases/mongo/8.0.3
    repoURL: file:///tmp/k8sexperiments.git
    targetRevision: HEAD
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true
