apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-jumpbox
  namespace: argocd
spec:
  destination:
    namespace: k8s-jumpbox
    server: https://kubernetes.default.svc
  project: infra
  source:
    path: cluster/infra/k8s-jumpbox
    repoURL: file:///tmp/k8sexperiments.git
    targetRevision: HEAD
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true
