apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-prometheus-operator
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: infra
  source:
    path: cluster/infra/k8s-prometheus-operator
    repoURL: file:///tmp/k8sexperiments.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
