apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: infra
  source:
    path: cluster/infra/k8s-argocd
    repoURL: file:///tmp/k8sexperiments.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
