namespace: kube-system
resources:
  - https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.7.2/components.yaml
patches:
  - target:
      version: v1
      kind: Deployment
      name: metrics-server
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value:
          --kubelet-insecure-tls
