apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubelet-monitor
spec:
  selector:
    matchLabels:
      k8s-app: kubelet
  namespaceSelector:
    matchNames:
      - kube-system
  endpoints:
    - port: http-metrics
      scheme: http
      path: /metrics
      honorLabels: true
      # tlsConfig:
      #   # caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      #   insecureSkipVerify: true
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
